In [2]:
import pandas as pd
# !pip install pandas


students = pd.Series(["Nazmul", "Rahim", "Karim"])

print(students)

0    Nazmul
1     Rahim
2     Karim
dtype: str

In [1]:
import pandas as pd

students = {
    "Name": ["Nazmul", "Rahim", "Karim", "Sakib"],
    "Age": [22, 23, 21, 24],
    "Marks": [85, 75, 90, 80]
}

df = pd.DataFrame(students)

print("Student Information")
print(df)

print("\nAverage Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())

top_students = df[df["Marks"] >= 80]

print("\nTop Students:")
print(top_students)

Student Information
     Name  Age  Marks
0  Nazmul   22     85
1   Rahim   23     75
2   Karim   21     90
3   Sakib   24     80

Average Marks: 82.5
Highest Marks: 90

Top Students:
     Name  Age  Marks
0  Nazmul   22     85
2   Karim   21     90
3   Sakib   24     80

In [1]:
student = {
    "name": "Nazmul",
    "age": 22,
    "cgpa": 3.75
}

for key, value in student.items():
    print(key, ":", value)

name : Nazmul
age : 22
cgpa : 3.75

In [2]:
import pandas as pd
data = {
    "Name": ["Nazmul", "Rahim", "Karim", "Sakib"],
    "Age": [22, 23, 21, 24],
    "Marks": [85, 75, 90, 80]
}

In [3]:
print(data)

{'Name': ['Nazmul', 'Rahim', 'Karim', 'Sakib'], 'Age': [22, 23, 21, 24], 'Marks': [85, 75, 90, 80]}

In [4]:
df = pd.DataFrame(data)
df

     Name  Age  Marks
0  Nazmul   22     85
1   Rahim   23     75
2   Karim   21     90
3   Sakib   24     80

In [5]:
df[df["Marks"] >= 80]

     Name  Age  Marks
0  Nazmul   22     85
2   Karim   21     90
3   Sakib   24     80

In [6]:
df['job'] = ['Engineer', 'Doctor', 'Artist', 'Teacher']
df

     Name  Age  Marks       job
0  Nazmul   22     85  Engineer
1   Rahim   23     75    Doctor
2   Karim   21     90    Artist
3   Sakib   24     80   Teacher

In [7]:
df = df.drop('job', axis=1)
df

     Name  Age  Marks
0  Nazmul   22     85
1   Rahim   23     75
2   Karim   21     90
3   Sakib   24     80

In [8]:
import pandas as pd
data = {
    "Name": ["Nazmul", "Rahim", "Karim", "Sakib"],
    "Age": [22, 23, 21, 24],
    "Marks": [85, 75, 90, 80]
}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df)

     Name  Age  Marks
a  Nazmul   22     85
b   Rahim   23     75
c   Karim   21     90
d   Sakib   24     80

In [34]:
filtered_df = df[df["Marks"] >= 80]
filtered_df.loc['a']

Name     Nazmul
Age          22
Marks        85
Name: a, dtype: object

In [10]:
df.loc[['b', 'c']]

    Name  Age  Marks
b  Rahim   23     75
c  Karim   21     90

In [11]:
df.iloc[0]

Name     Nazmul
Age          22
Marks        85
Name: a, dtype: object

In [15]:
df.loc[['b','a'],['Name', 'Age']]

     Name  Age
b   Rahim   23
a  Nazmul   22

In [16]:
df.iloc[0, [0, 1]]

Name    Nazmul
Age         22
Name: a, dtype: object

In [17]:
df.to_csv('output.csv')

In [18]:
df.to_csv('students.csv', index=False)
df.to_csv('students.csv', index=False, header=False)
df.to_csv('students.csv', index=False, header=['Student Name', 'Student Age', 'Student Marks'])

In [28]:
import sys

!{sys.executable} -m pip install openpyxl

df.to_excel('output.xlsx', index=False)

Requirement already satisfied: openpyxl in C:\Users\nazmu\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\nazmu\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)

In [29]:
df.to_excel('students.xlsx', index=False)

In [30]:
df.to_json('students.json', orient='records', lines=True)

In [32]:
import sys

!{sys.executable} -m pip install pyarrow

df.to_parquet('students.parquet', index=False)

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl (28.0 MB)
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/28.0 MB ? eta -:--:--
   -- ------------------------------------- 1.8/28.0 MB 7.3 MB/s eta 0:00:04
   --- ------------------------------------ 2.6/28.0 MB 5.8 MB/s eta 0:00:05
   ---- ----------------------------------- 3.4/28.0 MB 5.1 MB/s eta 0:00:05
   ----- ---------------------------------- 4.2/28.0 MB 4.7 MB/s eta 0:00:06
   ------- -------------------------------- 5.2/28.0 MB 4.4 MB/s eta 0:00:06
   -------- ------------------------------- 6.0/28.0 MB 4.3 MB/s eta 0:00:06
   --------- ------------------------------ 6.6/28.0 MB 4.3 MB/s eta 0:00:06
   ---------- ----------------------------- 7.6/28.0 MB 4.2 MB/s eta 0:00:05
   ----------- ---------------------------- 8.4/28.0 MB 4.1 MB/s eta 0:00:05
   ------------- -------------------------- 9.2/28.0 MB 4.1 MB/s eta 0:00:05
   -------------- ------------------------- 10.0/28.0 MB 4.0 MB/s eta 0:00:05
   --------------- ------------------------ 10.7/28.0 MB 4.0 MB/s eta 0:00:05
   ---------------- ----------------------- 11.5/28.0 MB 4.0 MB/s eta 0:00:05
   ----------------- ---------------------- 12.3/28.0 MB 4.0 MB/s eta 0:00:04
   ------------------ --------------------- 13.1/28.0 MB 3.9 MB/s eta 0:00:04
   ------------------- -------------------- 13.9/28.0 MB 3.9 MB/s eta 0:00:04
   -------------------- ------------------- 14.7/28.0 MB 3.9 MB/s eta 0:00:04
   ---------------------- ----------------- 15.5/28.0 MB 3.9 MB/s eta 0:00:04
   ----------------------- ---------------- 16.3/28.0 MB 3.9 MB/s eta 0:00:04
   ----------------------- ---------------- 16.8/28.0 MB 3.9 MB/s eta 0:00:03
   ------------------------- -------------- 17.6/28.0 MB 3.9 MB/s eta 0:00:03
   -------------------------- ------------- 18.4/28.0 MB 3.9 MB/s eta 0:00:03
   --------------------------- ------------ 19.1/28.0 MB 3.9 MB/s eta 0:00:03
   ---------------------------- ----------- 19.9/28.0 MB 3.9 MB/s eta 0:00:03
   ----------------------------- ---------- 20.7/28.0 MB 3.8 MB/s eta 0:00:02
   ------------------------------ --------- 21.5/28.0 MB 3.8 MB/s eta 0:00:02
   ------------------------------- -------- 22.3/28.0 MB 3.8 MB/s eta 0:00:02
   -------------------------------- ------- 23.1/28.0 MB 3.8 MB/s eta 0:00:02
   ---------------------------------- ----- 23.9/28.0 MB 3.8 MB/s eta 0:00:02
   ----------------------------------- ---- 24.6/28.0 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/28.0 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 26.2/28.0 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 27.0/28.0 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  27.8/28.0 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 28.0/28.0 MB 3.7 MB/s  0:00:07
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0

ArrowKeyError: No type extension with name arrow.py_extension_type found

In [35]:
filtered_df.to_csv('filtered_students.csv', index=False)

In [36]:
df

     Name  Age  Marks
a  Nazmul   22     85
b   Rahim   23     75
c   Karim   21     90
d   Sakib   24     80

In [37]:
import numpy as np
df['Marks'] = df['Marks'].replace(75, np.nan)
df

     Name  Age  Marks
a  Nazmul   22   85.0
b   Rahim   23    NaN
c   Karim   21   90.0
d   Sakib   24   80.0

In [38]:
import numpy as np
df['Marks'] = ['test',np.nan, 90, 80]
df

     Name  Age Marks
a  Nazmul   22  test
b   Rahim   23   NaN
c   Karim   21    90
d   Sakib   24    80

In [39]:
df.to_csv('students.csv', index=False)
df.to_csv('students.csv', index=False, header=False)
df.to_csv('students.csv', index=False, header=['Student Name', 'Student Age', 'Student Marks'])

In [40]:
left = pd.DataFrame({
    'key': ['A', 'B', 'C', 'D'],
    'value_left': [1, 2, 3, 4]
})

right = pd.DataFrame({
    'key': ['B', 'C', 'D', 'E'],
    'value_right': [5, 6, 7, 8]
})

In [41]:
left

  key  value_left
0   A           1
1   B           2
2   C           3
3   D           4

In [42]:
right

  key  value_right
0   B            5
1   C            6
2   D            7
3   E            8

In [43]:
merged = pd.merge(left, right, on='key', how='inner')
merged

  key  value_left  value_right
0   B           2            5
1   C           3            6
2   D           4            7